### ISSUE TITLE
Troublesome characters in folder names

### ISSUE THREAD

**Issue by tbartholomaus** [nsidc/qgreenland#214]
Hi QGreenland- thanks for setting this up- great resource.

I tried to look and see if I could resolve this myself in git, but it looks like not all the actual layers are on git.  I'm seeing through a fresh install (v0.54.0 downloaded today) a few troublesome filenames, with "bad" characters.  These are:

- the forward slash ('/') in the topo map scale: QGreenland_v0.54.0/Terrain models/Topographic map (1/500,000)/
- greater-than symbol ('>') in the earthquake magnitudes: QGreenland_v0.54.0/Geology/Earthquakes M>2.5 1900-2020/earthquakes.gpkg

Thanks!

**Comment by MattF-NSIDC** [comment]
Hey, thanks for opening our first GitHub issue :)

>a few troublesome filenames, with "bad" characters

How does this problem manifest for you? Do you see error messages? What operating system are you using, and what version of QGIS are you using?

**Comment by tbartholomaus** [comment]
I'm on a Mac (Big Sur) and QGreenland works just fine itself.  But I'm syncing my entire research directory to the cloud via MS One Drive, and One Drive (not QGIS or QGreenland) is giving me trouble about those two folder names.  I've already resolved it locally on my system by renaming the offending folders and fixing the links in QGIS.  But, in case this causes trouble for other users, you might change?  In general, I think some of these characters are problematic on some systems.  But if this is not your concern, then no worries!  Everything works great and you can close this issue!

**Comment by MattF-NSIDC** [comment]
@tbartholomaus We will be removing those troublesome characters from the layer titles before our v1.0.0 release. It turns out they are problematic for all Windows users!

**Comment by tbartholomaus** [comment]
Cool- I’m glad this works out!  Thanks again for your work on a great product!

**Comment by MattF-NSIDC** [comment]
Thank you for reporting a critical issue :)

**Comment by MattF-NSIDC** [comment]
This fix will be in the v1.0.0 release.
