### ISSUE TITLE
QGreenland data access API? 

### ISSUE THREAD

**Issue by EricKeenan** [nsidc/qgreenland#224]
Thanks for putting this package together! 

I'm wondering if there is a way to retrieve individual data files without first downloading the entire QGreenland package. This would be very helpful for butting together a mybinder notebook as part of the NSF EarthCube notebooks call.

**Comment by elynneh** [comment]
Hi Eric,

Thanks for your question! Currently there is no straightforward way to download individual data files and not the entire package. However, there are a couple of other ways you might be able to go about this: 1) You should be able to look at our configuration and find the source of the datasets you want to download if you are just interested in one or a few datasets. This could become tedious, though, if you want more than just a few data layers; 2) You can access our code on GitHub, make some configuration changes, and build a new customized QGreenland package for yourself. This solution is geared more towards an advanced user, and unfortunately we don't currently have documentation available for folks who aren't experienced users on how to do this. 

I hope this answers your question! Best of luck, and thanks again.

Cheers,
Lynne (QGreenland Team Member)

**Comment by EricKeenan** [comment]
Thanks @elynneh! I think this should work on a relatively small scale. I'll document what exactly I've done in case anyone else needs to do this in the future.

First, identify the layer url of interest in `qgreenland/config/datasets.yml`

Then retrieve using `wget`, e.g.
```
wget http://data.pgc.umn.edu/elev/dem/setsm/ArcticDEM/mosaic/v3.0/1km/arcticdem_mosaic_1km_v3.0.tif
```
