### ISSUE TITLE
Expose QGreenland data to the internet

### ISSUE THREAD

**Issue by mankoff** [nsidc/qgreenland#226]
Is there any way to access QGreenland data outside of the ZIP file here https://nsidc.org/qgreenland/stable/ ? 

Can you unzip that on the server into a 'data' or 'src' sub-folder so that we can access the layers individually? If so, you would provide alternate access methods that support older hardware, smaller disks, faster partial downloads, etc. I as a 3rd party can take care of all that via my own interface (probably using datalad).

**Comment by MattF-NSIDC** [comment]
@mankoff Apologies for the delayed response. We're currently in an active work period for QGreenland so we should be more responsive for the next couple of months.

We're currently considering doing exactly this, and building a QGIS plugin to act as an interface to automatically build out a partial environment tailored to your needs. We're not sure exactly when this work will be done.

**Comment by MattF-NSIDC** [comment]
Layers are exposed at http://qgreenland.apps.nsidc.org/layers/ and indexed with a `manifest.json`. This is an alpha feature in preparation for a QGIS plugin (or other tools) to be able to download a select subset of QGreenland layers. Let us know if you have any suggestions!
