### ISSUE TITLE
[Dataset]: World Ocean Atlas: ocean salinity

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#510]
### Dataset URL

https://www.ncei.noaa.gov/access/world-ocean-atlas-2023/

### Rationale

From: QGR-31

Since we already have temperature from WOA, we think it makes sense to get salinity from there as well.

An alternative might be CMIP5, but may be harder to work with: https://psl.noaa.gov/ipcc/ocn/details.html

**Comment by trey-stafford** [comment]
Closed by https://github.com/nsidc/qgreenland/pull/769
