### ISSUE TITLE
[Dataset upgrade]: Bedmachine to v5

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#513]
### Dataset URL

https://nsidc.org/data/idbmg4/versions/5

### More info

From: QGR-173

Probably little/no change in our processing. Here are the updates to the dataset:

>Added bathymetry measurements from the Alfred Wegener Institute,
Helmholtz Centre for Polar and Marine Research, in front of the Northeast Greenland Ice Stream
>
>Added ice thickness for ice caps from Millan et al. (2022) (https://www.nature.com/articles/s41561-021-00885-z)
>
>Included bathymetry data from NASA's 2021 Oceans Melting Greenland (OMG) campaign
>
>Provided a geotiff file of bed elevation

**Comment by MattF-NSIDC** [comment]
v4 is retired and can no longer be downloaded.

**Comment by trey-stafford** [comment]
https://github.com/nsidc/qgreenland/pull/544
