### ISSUE TITLE
[Bug]: `geothermal_heat_flow` 404s on fetch

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#519]
### Issue description

All 3 of the asset URLs for [this](https://github.com/nsidc/qgreenland/blob/main/qgreenland/config/datasets/geothermal_heat_flow.py) dataset are not fetchable. Does the URL need updating, or is the data no longer available?

### System information

N/A

**Comment by MattF-NSIDC** [comment]
@trey-stafford do you know the PR that resolved this?

**Comment by trey-stafford** [comment]
yes, https://github.com/nsidc/qgreenland/pull/546
