### ISSUE TITLE
[Dataset]: SDFI WMS satllite layers

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#528]
### Dataset URL

TODO

### Rationale

Has 1m satellite imagery for coast

**Comment by trey-stafford** [comment]
Waiting to hear back from Georg about WMS access.

SDFI requires users have a token to access their WMS services. We would need to redistribute a 'qgreenland' token and we're not sure yet if this is allowable.

**Comment by trey-stafford** [comment]
We should review the citation for this layer. Currently I have:

> Web service wms/gl_satellitfoto has been prepared on the basis
> of data from the Agency for Data Supply and Infrastructure and
> the following other institutions: Asiaq, the Geodata Agency,
> Landsplan, Nukissiorfiit, Oqaasileriffik and Tusass
