### ISSUE TITLE
[Dataset upgrade]: Add new SDFI topo map as WMS layer

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#529]
### Dataset URL

TODO

### More info

A new version was recently released. Ours is outdated.

**Comment by trey-stafford** [comment]
Waiting to hear back from Georg about WMS access.

SDFI requires users have a token to access their WMS services. We would need to redistribute a 'qgreenland' token and we're not sure yet if this is allowable.

**Comment by trey-stafford** [comment]
Georg got back to me, he says that he spoke with

> colleagues at “Dataforsyningen.dk” and it is ok to redistribute a token for
> QGreenland users. You just need to create a new token (using your existing
> login), and assign an expiration date (say in a year from now). And then when it
> is due to expire, you can extend the date.

> At the same time we would like for you, if possible, to inform QGreenland users
> that they can – free of charge – create there own login on the
> “Dataforsyningen.dk” for access to the SDFI services for Greenland.

**Comment by trey-stafford** [comment]
Given Georg's feedback, we should find out how long a token can go without being expired. Needing to manually refresh this token is likely to lead to our forgetting, especially after our current funding runs out. Maybe there's a way to automate this process?

We should also create a new "Dataforsyningen.dk” account for QGreenland if we don't already have one, and create the token with that account.

**Comment by trey-stafford** [comment]
We should review the citation for this layer. Currently I have:

> Web service wms/gl_aabent_land has been prepared on the basis
> of data from the Agency for Data Supply and Infrastructure and
> the following other institutions: Asiaq, the Geodata Agency,
> Landsplan, Nukissiorfiit, Oqaasileriffik and Tusass
