### ISSUE TITLE
[Bug]: Broken link to plugin docs in "stable" docs

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#533]
### Issue description

I think we need to cut a new release to fix this on "stable". Been a long while since I thought about this...

The broken link is on this page:

https://qgreenland.readthedocs.io/en/stable/tutorials/plugin-how-to.html

### System information

N/A

**Comment by trey-stafford** [comment]
We should also make a callout note that the plugin 

* was experimental
* no longer maintained
* not recommended for use. It probably does not work.

It would be good to add these items to the [qgreenland-plugin](https://github.com/nsidc/qgreenland-plugin/) repo as well (the README and the associated readthedocs).

**Comment by trey-stafford** [comment]
v3 release will fix the broken link issue. Creating a separate issue for creating a callout-note about the plugin.

**Comment by trey-stafford** [comment]
Closing because of the above comment.
