### ISSUE TITLE
[Dataset change] ocean temp layers to 'background' boundary

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#538]
Does the package get unreasonably large?

Can we use downsampling? Probably don't need full res for background layer.

The reason we gave up on this in the past was because cutting this layer to the 40° extent resulted in a weird ring-shaped cut where the only data extant afterwards is the data between 40°N and 41°N

I think it's worth taking one more stab at this now that we're using CLI OGR tools. Maybe it will be easier than wrangling the Python bindings?

Then again, maybe we already tried making this work at the CLI. See if @trey-stafford  remembers

**Comment by trey-stafford** [comment]
https://github.com/nsidc/qgreenland/pull/552

This adds ~2mb in file size to this layers but I think the context they provide is well worth it. Especially since we try to do this with other layers related to the ocean, like sea ice concentration.

**Comment by MattF-NSIDC** [comment]
Nice! Not worried about 2MB :)
