### ISSUE TITLE
[Dataset change] Consider removing alpha band from background layer

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#539]
The background layer has an alpha band that is not currently used and appears to be all-nan (double-check this). If this is the case, consider removing that alpha band!

QGIS does not seem to like the 4th band, the following error message gets logged repeatedly while this layer is toggled on:

```bash
ERROR 5: /share/appdata/qgreenland/working-storage/wip-package/QGreenland/Basemaps/Background (500m)/background.tif: GDALDataset::GetRasterBand(4) - Illegal band #
```

**Comment by trey-stafford** [comment]
The alpha layer is used. It is the mask band used in our JPEG-compressed background imagery. Without the alpha band, the "nodata" areas are not transparent (RGB values of 0,0,0)
