### ISSUE TITLE
[Dataset upgrade]: 2021 and 2022 sea ice concentration, extent, age 

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#541]

**Comment by trey-stafford** [comment]
PR to update sea ice age layers: https://github.com/nsidc/qgreenland/pull/549. 

Note that the PR only updates through 2021 because 2022 data is not yet available.

**Comment by trey-stafford** [comment]
PR to update the sea ice concentration layers: https://github.com/nsidc/qgreenland/pull/550

Note that I updated through 2021. We know the max extent for 2023  happened in March, so we could add it if we want. However, we would have to wait until after September to update the 2023 minimum, which will be after we wrap up publication of v3.

**Comment by trey-stafford** [comment]
We do  not need to update the sea ice extent layers because they are median extent lines based on the climatological period of 1981-2010.
