### ISSUE TITLE
Update place names layer (Asiaq)

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#553]
We want to update the Asiaq place names layer ("Places/Towns and settlements") because there are a number of noted data issues.

**Comment by trey-stafford** [comment]
According to Martin E. at Asaiq, we may already have the most up-to-date version of the data. However, he pointed me to this resource, which he thinks is based on the same dataset we already have: https://kort.nunagis.gl/portal/home/item.html?id=d9cf6eb788134a229076a8c855765e8c

That link itself links to an image service (MapServer...looks like the interface is ArcGIS hosted though), which is composed of two source layers:

* [Bygder (Settlements)](https://kort.nunagis.gl/refserver/rest/services/Kortportal/Byer_og_bygder/MapServer/0)
* [Byer (Cities)](https://kort.nunagis.gl/refserver/rest/services/Kortportal/Byer_og_bygder/MapServer/1)

I have been unsuccessful in fetching the source data for either of these layers (attempting to use the "query" interface returns a 404).

**Comment by trey-stafford** [comment]
This URL appears to work for querying the settlements layer: [https://kort.nunagis.gl/refserver/rest/services/Kortportal/Byer_og_bygder/MapServer/0/query/?f=json&where=OBJECTID+is+not+null&outFields=*&orderByFields=OBJECTID+ASC&returnGeometry=true&featureEncoding=esriDefault](https://kort.nunagis.gl/refserver/rest/services/Kortportal/Byer_og_bygder/MapServer/0/query/?f=json&where=OBJECTID+is+not+null&outFields=*&orderByFields=OBJECTID+ASC&returnGeometry=true&featureEncoding=esriDefault)

**Comment by trey-stafford** [comment]
PR to add place names from Asiaq/NunaGIS: https://github.com/nsidc/qgreenland/pull/570

**Comment by MattF-NSIDC** [comment]
@twilamoon-science can we pay someone to re-translate this dataset?

Background: We paid for someone to translate an earlier version of this placenames dataset to English, but a newer, more accurate version was released and it doesn't have English translations.

**Comment by trey-stafford** [comment]
Reviewing Jira tickets, I see we had a note about investigating "translation as a service" ([QGR-56](https://nsidc.org/jira/browse/QGR-56)). We might be able to leverage e.g., Google Translate API to provide rough translations for layers where Danish is used (it does not support translation to/from Greenlandic, however).

**Comment by trey-stafford** [comment]
Lets try to use our existing translations. Can we just adjust our preprocess script to join our translations to the latest version of cities/settlements?

**Comment by twilamoon-science** [comment]
If this process looks promising, we can use it for the QGreenland layer and *ask Asiaq if they would consider amending their dataset of record to include the translated version also*.

**Comment by trey-stafford** [comment]
I reviewed our translation process for the original Asiaq placenames database and found that most of the translation work cannot be applied to the updated place names layers we pull from NunaGIS.

The Asiaq placenames database includes placenames for various points of interest (e.g., lakes, beaches, radio stations, places to pick berries, etc.). These object designations are what we have translations for. The cities and settlements layers pulled from NunaGIS are just that - cities and settlements. 

Moreover, the new cities and settlements layers have fewer fields than the original Asiaq placenames database. The newly updated layers have fields for:

* New Greenlandic
* Old Greenlandic
* Danish
* Alternative placename

The original placenames database also included fields for:

* Object designation
* Source
* Municipality
* Notes
* Date of registration
* Modification date
* Authorized
* Project manager
* DMS longitude
* DMS latitude
* KMS cartography
* Namer

The one thing we can translate is the field names (e.g., "Ny grønlandsk" -> "New Greenlandic").

**Comment by MattF-NSIDC** [comment]
>The Asiaq placenames database includes placenames for various points of interest (e.g., lakes, beaches, radio stations, places to pick berries, etc.). These object designations are what we have translations for.

Didn't get this at first, but looking at the translation data helped. An example translation record:

```
ANKER,"Ankerplads, naturlig havn",Umiatsialivilik,11,"Anchorplace, natural harbor"
```

**Comment by trey-stafford** [comment]
The new layers added in the associated PR also include a population (2016) field. This may meet the requirements of https://github.com/nsidc/qgreenland/issues/596

There have definitely been changes in population since 2016, but at least this might give those who are looking an idea of numbers. E.g, The settlement of Illorsuit has a population (2016) of 75. However, we know that Illorsuit was abandoned in 2017 due to a landslide and tsunami event.

**Comment by trey-stafford** [comment]
Now ready for review: https://github.com/nsidc/qgreenland/pull/570
