### ISSUE TITLE
GEUS 1:500k geological map

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#566]
* Joe M. has a link to some data. It’s apparently really large but we could point users to it.

* Someone at GEUS noted making a QGIS compatible version of the dataset from Joe M.

**Comment by trey-stafford** [comment]
Paper for dataset: https://geusbulletin.org/index.php/geusb/article/view/4727/10367

It notes:

> The new seamless map has been integrated in such a  Web-GIS  application  which  can  be  found  at  http://data.geus.dk/map2/geogreen.

However, attempting to access the given URL gives a "service unavailable" page (HTTP 503)

It also notes:

> The  seamless  map  is  furthermore  an  important  GEUS  contribution  to  the  global  OneGeology  portal  (http://por-tal.onegeology.org). This portal aims to put geological maps from all countries in the world together on a scale of 1:1 mil-lion or better, by using distributed web map services (WMS). The geological map of Greenland on this portal is currently a 1:2 500 000 scale map. The new 1:500 000 map will fulfil GEUS’ participation in this important international initia-tive.

However, the map does not appear to be there either. There is a " GEUS Geology of Greenland " WMS service available from onegeology but it notes:

> Available in this OGC WMS service for personal, non-commercial use only 

We're non-commercial but not for 'personal' use. I tried their web portal and it seems very slow/unresponsive.

**Comment by trey-stafford** [comment]
A WMS version of the map is available via GEUS: https://data.geus.dk/arcgis/rest/services/Greenland/Geological_map_500k/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

However, there does not appear to be a legend (the link to the legend is broken, 404).

Moreover, [this page](https://maps.greenmin.gl/geusmap/ows/help/?mapname=greenland_portal&epsg=32624) notes:

> * We have limited hardware ressources. Use our services responsibly. If in doubt, contact us!
> * If email is added to the service-URL, we can better monitor usage and give feedback. Anonymous users might be refused during peak hours.

**Comment by trey-stafford** [comment]
There are some vector data available via https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/FWX5ET. The data are stored in an `mpkx` format ([Esri Map Package](https://pro.arcgis.com/en/pro-app/latest/help/sharing/overview/map-package.htm))

Downloading the dataset requires that the user acknowledge their "Dataset Terms":

> This data set and documentation (hereafter 'Data') is covered by the following terms of use.
> 
>  
> 
> Rights
> 
> The 'Data' are subject to copyright by the Geological Survey of Denmark and Greenland (hereafter GEUS).
> The user has a nonexclusive right to use the 'Data' for internal purposes only, including the right to process the 'Data', the right to data extraction from the 'Data', and the right to make one safety copy of the 'Data' for own use only.
> The user is not entitled to produce or transfer to third parties products based on processed 'Data', unless it is for pure non-commercial information purposes within the user's field of business/field of competence. However, the user is not entitled to produce or transfer to third parties new maps based fully or partly on processed 'Data'.
> The user's rights according to these terms of use may be utilised by individuals employed by the user or with any fully controlled subsidiaries of the user. Furthermore, the user is entitled to make the 'Data' available to contractors, consultants and the like in connection with work undertaken for the user. In this event, the 'Data' may only be made available to others to the extent dictated by the specific purpose.
> If the user is a consultant or the like, who downloads the 'Data' for the purpose of performing work for a customer, the ”for internal purposes” may be extended to cover ”the customer's internal purposes”, which is conditioned upon the term that 'Data' (original as well as processed 'Data') is transferred to one customer only. If the User is a municipality, county or another governmental body within the Kingdom of Denmark, including Greenland and the Faroe Islands, ”for internal purposes” may include the user's right to use the 'Data' for administrative purposes within its jurisdiction, including handling of specific cases, and for planning purposes, including preparation of regional plans etc.
> Furthermore, the user is entitled to make the 'Data' (original as well as processed 'Data') available to other governmental bodies or private individuals as part of the handling of specific cases for the user.
> 
>  
> 
> Redistribution
> 
> The use is not entitled to copy, publish, resell, lend or rent samples of the 'Data' or part hereof or otherwise redistribute the 'Data' (original as well as processed 'Data') in any other way than described in the section above without the prior written consent of one of the copyright holders.
> If the 'Data' are redistributed or otherwise made available to third parties in accordance with the section above or in accordance with a specific written agreement, the user is obliged to inform the third party of and impose on him the obligation to respect GEUS’ and MMR’s rights according to the present terms of use.

**Comment by trey-stafford** [comment]
Blocked until we contact GEUS

**Comment by MattF-NSIDC** [comment]
When we do contact GEUS, we might mention that the license terms are a bit vague.

**Comment by trey-stafford** [comment]
I was about to send an email to Niels when I realized that we probably had already asked this question of GEUS before. Indeed, we have! Back in Dev. 2020, we asked for permission to include data from the PROMICE portal and also the 1:500 000 geological map!

We never got a definitive answer back, as far as I can tell. I'm going to wait to get in touch with Niels or follow up on the existing email thread ("RE: Permissions follow up to seek GEUS permission for including data within QGreenland") until we chat with Twila since she was the primary point of contact.

Here's the email text I was about to send:

> Hey Niels,
> 
> I hope you are doing well! The QGreenland team has been hard at work preparing v3 of our core data package, which we expect to release later this summer (probably late August).
> 
> One of the datasets we are currently considering for v3 of QGreenland is the "Seamless digital 1:500 000 scale geological map of Greenland, version 2.0" dataset found on the GEUS dataverse (https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/FWX5ET). Our only hesitation about this dataset right now is related to its License/Data Use Agreement. It has "custom dataset terms" which we have some uncertainty over.
> 
> It states:
> 
> >    The user is not entitled to produce or transfer to third parties products based on processed 'Data', unless it is for pure non-commercial information purposes within the user's field of business/field of competence.
> 
> Since we are a non-commercial group who would be redistributing the data for educational purposes, I think we meet this requirement. However, the license also states:
> 
> >    However, the user is not entitled to produce or transfer to third parties new maps based fully or partly on processed 'Data'.
> 
> We do not think that redistributing the data via QGreenland would constitute a 'new map' necessarily, but given this language we wanted to double-check with you and/or others at GEUS who may have thoughts on this. Do we have permission to include this data in QGreenland? We would, of course, include full attribution/citation information and provenance for the data.
> 
> Please let us know what you think! We appreciate your time and assistance!
> 
> 
> Trey Stafford, on behalf of the QGreenland team

**Comment by trey-stafford** [comment]
Lets continue the thread in the QGreenland email. I'll follow up.

**Comment by trey-stafford** [comment]
I followed-up with GEUS about this today via QGreenland's email. Hopefully we hear back soon that we can use the data in QGreenland v3!

**Comment by twilamoon-science** [comment]
If we do not receive permission for direct distribution, this should be a dataset that we highlight as an add-on (like with the ArcticDEM custom Greenland dataset and the ADC QGreenland Data Portal). Want to make sure @alysethurber has this in mind for website update - we do want these few specific add-on/data sources top and center on the "Data" page.

**Comment by MattF-NSIDC** [comment]
This won't make it in v3.

**Comment by MattF-NSIDC** [comment]
_Actually_, we got an email from GEUS ~6 hours ago that clears us to use this dataset!

**Comment by trey-stafford** [comment]
The dataset provided via the [GEUS dataverse](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/FWX5ET) is a zip package containing an  [Esri Map package](https://pro.arcgis.com/en/pro-app/latest/help/sharing/overview/map-package.htm) (`.mpkx`). 

This map package is a 7zip compressed directory that includes esri-specific metadata and datasets. 

After unzipping the data, I see two directories (`p20` and `p30`), each of which have a `g500_2023_pro.gdb` directory. These `gdb` directories are [geodatabases](https://pro.arcgis.com/en/pro-app/latest/help/data/geodatabases/manage-file-gdb/file-geodatabases.htm). 

The geodatabases contain vector layers that appear to be the same for both the `p20` and `p30` directories. They are given by `gdalinfo`:

```
$ ogrinfo p20/g500_2023_pro.gdb
INFO: Open of `p20/g500_2023_pro.gdb'
      using driver `OpenFileGDB' successful.
Layer: g500_geopoint_line_anno (Multi Polygon)
Layer: g500_rivers_arc (3D Multi Line String)
Layer: g500_geopoint_line (3D Multi Line String)
Layer: g500_geology_trends (3D Multi Line String)
Layer: g500_contours_arc (3D Multi Line String)
Layer: g500_geology_arcs (3D Multi Line String)
Layer: g500_geology_polygon (3D Multi Polygon)
```

These layers are easy enough to extract and can be opened in QGIS. The main problem is related to symbology.

The symbology for these layers is important, and the configuration for it appears to be specific to Esri products. I am not sure yet if we can convert these styles into something with QGIS.

Each layer on its own has limited value, and it seems like having them all visualized together is important to interpreting the map For example, features in the `g500_geopoint_line` layer appears as various straight lines when added to QGIS, but the map as it's supposed to be symbolized represents these lines as arrows of different types depending on the attributes of the feature.

The image below shows one such feature highlighted. Other features from this layer can be seen as red lines.

![Image](https://github.com/nsidc/qgreenland/assets/19692879/9f08a7a4-7c62-4ca9-b640-939606f3e1d3)

I plan to do a little more digging into if we can convert the styles from Esri to something compatible with QGIS, but my instinct right now is that this might be more effort than it's worth. Instead, it may be more reasonable to just add this layer as an online-only resource (https://data.geus.dk/arcgis/rest/services/Greenland/Geological_map_500k/MapServer/).

**Comment by MattF-NSIDC** [comment]
Nice sleuthing. I think adding it as an online layer is a good temporary compromise. Maybe in the meantime, this dataset becomes more FAIR and easier to add.

**Comment by twilamoon-science** [comment]
It's kind of blowing my mind that they build the archived dataset this way. I agree that it's reasonable to do a bit more digging (also just interesting learning) but that online-only may be the final conclusion. When I linked to the site I didn't see an option for viewing with QGIS. Is that something we do via one of the other viewing methods they list prominently (all proprietary  :(  )?

**Comment by trey-stafford** [comment]
> I think adding it as an online layer is a good temporary compromise. 

Agreed.  If we go this route I would probably follow up with GEUS again and explain our plan/reasoning. They request a `whoami` parameter be set with an email address. I think using the qgreenland info email would probably work.

> It's kind of blowing my mind that they build the archived dataset this way.

My guess is that they developed the map & all of it's symbology in Esri products (ArcGIS), which they host a view of via the web map service I mentioned above. When it came to publishing the data, saving it as a map package was probably just a  convenient choice. Unfortunately that means hose of us without an ArcGIS license have to do some extra legwork.

I wonder if they could easily publish a raster (e.g., GeoTiff)...maybe it's something we could suggest.

> When I linked to the site I didn't see an option for viewing with QGIS. Is that something we do via one of the other viewing methods they list prominently (all proprietary :( )?

I'm not sure QGIS can read the `.mpkx` file directly. I manually unzipped it and then accessed the `gpd` databases from QGIS (add as vector).

**Comment by trey-stafford** [comment]
At least one tool exists for convering ArcGIS .mapx packages into something compatible with QGIS. It's a tool called [slyr](https://north-road.com/slyr/), produced by a company called North Road. It has a pricey license at 1200 euro. I strongly prefer to look elsewhere before giving this any serious consideration, but I thought I would take note of it.

Funnily, one of the examples they have on their website is a collection of geology related layers! We're not the first ones with this problem.

**Comment by trey-stafford** [comment]
PR for adding the layer as online-only: https://github.com/nsidc/qgreenland/pull/725/files

I plan to follow-up with GEUS to let them know that  we plan to utilize their WMS service.

**Comment by twilamoon-science** [comment]
Thanks @trey-stafford. In your contact with them, a brief note on what was attempted and the problem we encountered would be good to include. And an inquiry on whether they would expect to update/add other formats at some point.

**Comment by trey-stafford** [comment]
> After unzipping the data, I see two directories (p20 and p30), each of which have a g500_2023_pro.gdb directory

This might explain why there are two versions of the geodatabase in the `.mpkx` map package: https://community.esri.com/t5/arcgis-pro-questions/why-is-there-a-p20-and-p30-folder-when-i-open/td-p/1271259

**Comment by trey-stafford** [comment]
Should we keep the existing geological map from the Canadian geological survey?

**Comment by twilamoon-science** [comment]
I think since the GEUS map will be internet-only, it makes sense to keep the current download geological map layers too.

**Comment by trey-stafford** [comment]
Here's a screenshot of the styles applied to the polygon and geopoint line layers:

![Image](https://github.com/nsidc/qgreenland/assets/19692879/677f7d7b-44ca-4344-a357-9d24ba0db0ec)

**Comment by trey-stafford** [comment]
Given these issues, sticking with the WMTS online-only layer still seems like the right choice. We can re-open if we learn more or come up with another solution.

**Comment by twilamoon-science** [comment]
Yes, good call. In responding to GEUS, please let them know of this decision and that we would like notification if/when they make further updates. Of course, do tell them you tried this and relate the issues.

**Comment by trey-stafford** [comment]
GEUS provided us with `.sld` style files for some of the layers, which QGIS can natively read:

* `g500_rivers_arc`
* `g500_geology_trends`
* `g500_contours_arc`
* `g500_geology_arc`
* `g500_geology_polygon`

Note that SLD styles were not provided for the geopoint or annotation layers. Our contact at GEUS noted that the geopoint style in particular was giving them trouble, but that they will let us know once it is resolved.

Two of the provided `.sld` styles did not work at first - I had to manually edit the rules for applying different styles based on an attribute, but it wasn't too difficult.

Screenshot of the result below:

![Image](https://github.com/nsidc/qgreenland/assets/19692879/49a3a16e-efd4-4fe7-b677-f6df8c1e87bb)



![Image](https://github.com/nsidc/qgreenland/assets/19692879/408c4b4f-4034-493c-b08d-5db9234a4cfd)


Compare that to the WMS layer:


![Image](https://github.com/nsidc/qgreenland/assets/19692879/18f59bd5-cb8d-41ad-8fc3-a986714de0a0)


![Image](https://github.com/nsidc/qgreenland/assets/19692879/90609e6b-3bf8-4c20-b7d5-ddbd3a59d3f3)


Assuming we want to add these layers, I'll need to do some more research on what each of these actually represent so that I can put something useful in the 'description'. Maybe GEUS can help us with that!

**Comment by MattF-NSIDC** [comment]
Sounds like we're in closer contact now, so that's good!

**Comment by trey-stafford** [comment]
Draft PR: https://github.com/nsidc/qgreenland/pull/739

**Comment by trey-stafford** [comment]
We plan to stick with the WMS version.

The styles as defined work, but causes visualization to be extremely slow. Moreover, we agreed upon review that the layer order and symbolization provided by GEUS are still key to interpretation (e.g., many polygons have NULL descriptions but their symbology still indicates the geological unit type), so a rendered view (e.g., from WMS) makes the most sense. The main drawback is the need for a separate legend that has to be downloaded (pdf) and used alongside the layer.

Note that I did just try re-configuring the symbology for the polygon layer to use the "categorization" type using the `gm_label` as the value and the layer now performs just fine. Maybe there's a way to convert a rule-based style into a categorization style (we could likely write some code to do this too), but given our limited time the best solution right now is to communicate our findings to GEUS.

**Comment by twilamoon-science** [comment]
Plus, mentioning any elements that we were successful with (e.g., your experiment with "categorization" type) can help GEUS to provide guidance to other users and continue to improve the data on their end.

**Comment by MattF-NSIDC** [comment]
>Note that I did just try re-configuring the symbology for the polygon layer to use the "categorization" type using the gm_label as the value and the layer now performs just fine

Great find!

**Comment by trey-stafford** [comment]
Just sent a reply to our email thread with GEUS. Closing this issue for now!
