### ISSUE TITLE
Consider alternative earthquakes dataset

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#572]
We had some feedback that the USGS earthquakes layer is not very good. We were directed to GEUS:

* http://seis.geus.net/projects/glisn/geus-eqlist.html
* https://eng.geus.dk/nature-and-climate/earthquakes-and-seismology

Consider if we can ingest and use this data. If so, should we keep the USGS layer or replace it entirely?

**Comment by MattF-NSIDC** [comment]
These layers might be heavier lifts because of the strange text-embedded-in-a-webpage format. What is "the Nordic format"?

**Comment by trey-stafford** [comment]
The nordic format specification can be found here: http://seis.geus.net/software/seisan/node243.html

The format depends on the position of characters (every line is 80 characters). Attempts to parse the data from the HTML were mixed as a result. I initially tried replacing whitepsace with a `,` to produce a csv but that fails in cases where two values _aren't_ separated by whitespace. I think we would have to write some code to:

1. Parse the HTML and extract the records. These are between two `pre` tags.
2. Convert the data from nordic format to e.g., csv using character ranges to extract values
3. Then, `ogr2ogr` or whatever other processing would be necessary to produce a `gpkg`.

Moreover, it's indicated that the data on the webpage are generated from a database, but no api appears to exist to interact with that database directly (or to query it for data in a different format). This makes the possible solution above somewhat brittle  - if the format of the webpage changes, our code would need to as well, even if the format of the data inside the page remains the same.

There is a [GEUS Dataverse](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/ABMBLO) entry for "Cryo-generated Seismic Events in Greenland" with a public domain license, however. The data from this are in csv and a variant of the nordic format.  The csv only has datetime and location. The nordic version contains much more information but it's format is more complex and would also need some custom code to extract a useful GIS dataset.

**Comment by MattF-NSIDC** [comment]
>The nordic format specification can be found here: http://seis.geus.net/software/seisan/node243.html

Nice!

>The format depends on the position of characters (every line is 80 characters).

:scream: I'm having COBOL flashbacks! Someone throw water on me!

Agree about extracting data from HTML being brittle, I'd like to avoid. There are things we can do to mitigate, but can only go so far to protect ourselves from changes made by outside parties.

>There is a GEUS Dataverse entry ... The nordic version contains much more information but it's format is more complex and would also need some custom code to extract a useful GIS dataset.

But at least we wouldn't have to extract the "nordic format" data from an HTML page! That's a step in the right direction :) But the spec looks like it has a lot more complexity than the simple tabular data we were originally looking to read.

 Have you looked at this? https://github.com/saeedsltm/PyNordicRW

**Comment by trey-stafford** [comment]
PR that adds the location of "cryo-generated" seismic events from the [GEUS Dataverse](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/ABMBLO) entry: https://github.com/nsidc/qgreenland/pull/708. I lean toward declining this PR in its current state since a user would need to link this location data with additional information to be useful (which is in a Nordic-formatted file).

I'll take a look at the `PyNoridcRW` code linked above.

**Comment by trey-stafford** [comment]
`PyNoridcRW` is written for Python 2 and does seem to produce some structured data from [cryo.nor](https://seis.geus.net/quakes/cryo.nor) NORDIC-formatted data file provided by the [GEUS Dataverse](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/ABMBLO) entry for "Cryo-generated Seismic Events in Greenland":

```
>>> from PyNordicRW import Read_Nordic
>>> info = Read_Nordic(inp='cryo.nor')
+++ Skipping Phase! Check Line-4 at event => 20070813203440.2
+++ Skipping Phase! Check Line-4 at event => 20070813203440.2
+++ Skipping Phase! Check Line-4 at event => 20101103080017.8
+++ Skipping Phase! Check Line-4 at event => 20110102044715.3
+++ Skipping Phase! Check Line-4 at event => 20120808005341.9
...<clipped for brevity>...
+++ Skipping Phase! Check Line-4 at event => 20230712193722.1
>>> len(info.keys())
1921
>>> info['20070813203440.2']['HEADER']['L1'].keys()
['F1', 'Year', 'F2', 'Month', 'Day', 'FO', 'Hour', 'Min', 'F3', 'Sec', 'LMI', 'DI', 'EID', 'Lat', 'Lon', 'Dep', 'DepI', 'LocI', 'AGC', 'NumS', 'RMS', 'Mag1', 'TMag1', 'MAGC1', 'Mag2', 'TMag2', 'MAGC2', 'MAG3', 'TMag3', 'MAGC3', 'TL']
```

Each entry has a header with lat/lon, date/time, and some other useful metadata.

**Comment by MattF-NSIDC** [comment]
>I lean toward declining this PR in its current state since a user would need to link this location data with additional information to be useful

Agree!

**Comment by MattF-NSIDC** [comment]
> `PyNoridcRW` is written for Python 2 and does seem to produce some structured data from the [cryo.nor](https://seis.geus.net/quakes/cryo.nor) NORDIC-formatted data file provided by the [GEUS Dataverse](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/ABMBLO) entry for "Cryo-generated Seismic Events in Greenland"

Neat. There is no license on that repository, unfortunately. We could always write and package a nordic format parsing library for modern Python... :)

**Comment by trey-stafford** [comment]
Yeah, and I'm not sure I trust `PyNordicRW` to parse all of the information correctly. Given the current difficulties around utilizing this data and providing a good linkage between locations of events and their associated data in nordic format, I am going to close this issue.

To summarize:

* The GEUS earthquakes data (http://seis.geus.net/projects/glisn/geus-eqlist.html) is embedded in a webpage. There does not seem to be a proper dataset associated with this table, just an indication that it was generated from a database. We do not want to extract data embedded in a webpage
* The "Cryo-generated Seismic Events in Greenland" dataset published on the GEUS Dataverse, like the earthquakes dataset, is in nordic format. In this case, the data are published in a way we can fetch the data directly, but we would still need to write a parser to link the location data to useful metadata (or maybe figure out how to utilize [SEISAN](http://seis.geus.net/software/seisan/seisan.html) .

**Comment by MattF-NSIDC** [comment]
>We do not want to extract data embedded in a webpage

:100:
