### ISSUE TITLE
Frozen ground layer updates/additions

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#591]
There are 3 "Frozen ground/" layers currently:

* "Ground temperature 2000-2016 (10km)" 
* "Ground temperature standard deviation (10km)"
* "Permafrost probability (10km)"

All three of these layers  are from Obu et al., 2018:

```
Obu, Jaroslav; Westermann, Sebastian; Kääb, Andreas; Bartsch,
Annett (2018): Ground Temperature Map, 2000-2016, Northern
Hemisphere Permafrost. Alfred Wegener Institute, Helmholtz
Centre for Polar and Marine Research, Bremerhaven, PANGAEA
```

https://doi.org/10.1594/PANGAEA.888600

This dataset does not have an update with more recent data.

Are there other datasets we could add? Newer dataset we could use to replace the above?

Twila suggests reaching out to colleagues for suggestions:

* [Ted Schuur](https://ecoss.nau.edu/team/ted-schuur/)
* [Christina Schaedel](https://www.woodwellclimate.org/staff/christina-schaedel/)
* [Dr. Sharon Smith](https://profils-profiles.science.gc.ca/en/profile/dr-sharon-smith)

**Comment by trey-stafford** [comment]
I reached out to Ted, Christina, and Sharon via our QGreenland email account. We shall wait to hear more!

**Comment by trey-stafford** [comment]
Christina suggests that we look into the [Circumpolar Active layer Monitoring network (CALM)](https://www2.gwu.edu/~calm/data/north.htm)

**Comment by trey-stafford** [comment]
Sharon suggests that we should look into data related to the following publications:

> Strand, S.M., Christiansen, H.H., and Gilbert, G.L. 2022. Permafrost thermal dynamics and cryostratigraphy at Villum Research Station, Station Nord, eastern North Greenland (81°N). Journal of Geophysical Research: Earth Surface, 127: e2021JF006502. doi:10.1029/2021JF006502

> Strand, S.M., Christiansen, H.H., Johansson, M., Akerman, J., and Humlum, O. 2021. Active layer thickening and controls on interannual variability in the Nordic Arctic compared to the circum-Arctic. Permafrost and Periglacial Processes, 32: 47-58. doi:10.1002/ppp.2088

She also suggests reaching out to Strand or Christiansen (first two authors in the above references) for more information.

**Comment by trey-stafford** [comment]
[This Jira ticket](https://nsidc.org/jira/browse/QGR-24) states:

https://nsidc.org/data/GGD318/versions/2

Available as ESRI shapefile and EASE-Grid. Gridded data are gridded at 12.5 km, 25 km, and 0.5 degree resolution

Comment: 


> We ended up using the raster gridded data and releasing that. (v0.20.0?)

> Should we still bother with the vector data?

On 12/16/2021 Matt noted we're no longer interested in this data. Still True?

> We're not interested in this dataset right now.

**Comment by trey-stafford** [comment]
https://gtnp.arcticportal.org/resources/maps/12-resources/38-maps-active-layer-grids: The maps of Active Layer Thickness Monitoring sites display the location of all monitoring sites contained in the GTN-P database.

Data are provided as a shapefile of points and includes sites in Greenland. Attributes include site name, id, borehole number, and start/end dates. A user of this layer would need to go to the GTN-P database to get data for each of the sites.

**Comment by MattF-NSIDC** [comment]
>On 12/16/2021 Matt noted we're no longer interested in this data. Still True?

>>    We're not interested in this dataset right now.

I think I was taking notes from a decision made on a meeting. I should have added more context. I don't remember anything else :(

**Comment by MattF-NSIDC** [comment]
Trey found CALM locations also available at [GTN-P](https://gtnp.arcticportal.org/) but it only contains data up to 2017. There's also a copyright notice on their website to not re-distribute this data.

**Comment by trey-stafford** [comment]
Given there are no other active suggestions for frozen ground layers right now, closing.
