### ISSUE TITLE
[Bug]: Vegetation classification map includes some non-vegetation classifications

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#594]
### Issue description

Should we make the freshwater, saline water, and other non-vegetation classes transparent so that other layers can more easily be used with this layer?

### System information

N/A

**Comment by MattF-NSIDC** [comment]
This is a style-only change, should be easy.

**Comment by twilamoon-science** [comment]
If this is a quick fix, perhaps move above v3 release in priority?

**Comment by MattF-NSIDC** [comment]
I think maybe this shouldn't have been marked "Ready" because we need to decide whether hiding the non-vegetation classifications is the right path forward.

Do you think we should set them as hidden (downside is that the full scope of the available data would be hidden from users), or leave them all visible and let users hide the things that are irrelevant to them (downside is that this classification map, by default, covers everything beneath it)? I'm leaning towards the latter, because it provides the most information to the user to make their own decision.

**Comment by twilamoon-science** [comment]
I agree that non-vegetation categories should not be hidden. But instead hopefully an obvious category that folks could turn on/off? Or at least just obvious in the legend info.

**Comment by MattF-NSIDC** [comment]
Here's what the legend and map look like today: 
![image](https://github.com/nsidc/qgreenland/assets/18539827/a4e0de99-b6fc-4e8d-ba0d-dccbcdde1638)

If the user doesn't know how to make a classification transparent, they may have trouble. I imagine a user might try to click or double-click a classification. If they do the latter, the Layer Properties window opens:

![image](https://github.com/nsidc/qgreenland/assets/18539827/934245ab-eed2-4ed0-90a7-6b9ed4e8331e)

It doesn't default to the symbology or transparency tab, though. They'd need to go to the transparency tab to add new transparent values (IMO the more correct option), or to go to the symbology tab to delete a classification.

It would be really nice if QGIS offered the ability to hide a classiciation directly from the legend, but at least in 3.28.x that's not the case. We could open a feature request!

**Comment by twilamoon-science** [comment]
I agree that it's ready to close. We'll keep our eyes out for something better for the future, and reflect what we can in the metadata. Thanks.

**Comment by MattF-NSIDC** [comment]
I think I see what you mean, the `NA` "Non-arctic" classification? It's weird to me that the "Non-arctic" zone is surrounded by valid classications like "glacier" and "Prostrate dwarf-shrub" on all sides. :shrug: In any case, do agree it's valuable context!

Closing :)
