### ISSUE TITLE
Layer updates

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#602]
(Originally authored by @trey-stafford )

Holding place to record notes about layers that may or may not be updated (is there an updated source?)

Also, is there a good way to find out which layers need to be re-fetched to get the latest (e.g., earthquakes)?

  * I had thought there was some mechanism in place for clearing the cache of layers tagged a certain way, but that doesn't seem to be the case...

Layers:

*  ~~Reference/Greenland municipalities and population 2019~~ 
    * No apparent update available. 
* ~~environmental management mineral and hydrocarbon licenses. ~~
  * ~~This does have updates. We just need to clear the cache and re-fetch from source to get the updates. Noted in https://github.com/orgs/nsidc/projects/11/views/1?pane=issue&itemId=30929829~~
* ~~Protected zones layers~~ 
  * This layer is no longer available from where we originally fetched it.
* ESA CCI products
  * ~~Glaciology/Surface elevation change: [new dataset](http://products.esa-icesheets-cci.org/products/details/cci_sec_2021.zip/)~~ https://github.com/nsidc/qgreenland/issues/574
  * ~~Supraglacial lakes?~~
      * ~~There is a new [dataset for 79 and Zachariae Glacier catchments for 2019/05/01-2019/10/01 using S2 data](http://products.esa-icesheets-cci.org/products/details/greenland_sgl_s2_20190501_20191001_79_v1_1.zip/), but it is >1GB in size. I downloaded the dataset and took a look at the contents. It includes a shapefile with polygons deliniating subglacial lakes in NE Greenland. There are around 26k records. Converting the Shapefile to a GeoPackage results in a file size of 998M.~~ https://github.com/nsidc/qgreenland/issues/665
  * ~~Ice velocity~~ https://github.com/nsidc/qgreenland/issues/663
      * ~~[Dataset that includes data from 2018-2021](http://products.esa-icesheets-cci.org/products/details/greenland_iv_100m_s1_insar_s20181201_e20210301_v1.0.zip/). This has a longer temporal range than our current layer (2019-2020) and at a higher spatial resolution (100m instead of 250m) but coverage is not complete over Greenland.~~
*  ~~research stations? GEM and Promice stations may need updated?~~ https://github.com/nsidc/qgreenland/issues/588
    * ~~Our current source for Promice/GC-NET has no updates. However, there is a [dataset from 2023](https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/IW73UU) that has a `AWS_metadata.csv` that appears to have station locations & other metadata for PROMICE and GC-Net  as well as others like Glaciobasis~~
    * ~~GEM Does not need updating~~
* ~~albedo~~ (https://github.com/nsidc/qgreenland/issues/662)
    * ~~There is a MODIS derived dataset that has monthly data through 2019: https://dataverse.geus.dk/dataset.xhtml?persistentId=doi:10.22008/FK2/HVVUX4. Our current dataset just has July 2018 and 2019 available and is derived from Sentinel-3A.~~

**Comment by trey-stafford** [comment]
Closing this ticket because each layer-related item has been resolved or moved to a new issue.
