### ISSUE TITLE
Ensure prod cleanup does not remove previously released packages

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#605]
Migrated from [Jira](https://nsidc.org/jira/browse/QGR-89): 

`./scripts/cleanup.sh` (spelling?) removes releases, and should not be run in production. I learned that lesson the hard way with v0.20.0 where I deleted all the older releases. We can regenerate them if we want but that would be time consuming and I'd rather roll forward. But we should fix the script so that if anyone, like me again, forgets not to run it, production will be safe.

**Comment by MattF-NSIDC** [comment]
I think since v0.20.0 we changed the script to require intentionally requesting releases to be deleted. TODO: Verify this is the case; if so, close ticket.

**Comment by MattF-NSIDC** [comment]
Verified, you have to pass a specific flag to get released packages to be deleted.
