### ISSUE TITLE
Sentinel-2

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#623]
Migrated from [Jira](https://nsidc.org/jira/browse/QGR-25):

Comment:

 >  Hold on this until we have a location to pull from.

Comment:

 >   Twila to contact data provider to find an archived version of this data

**Comment by trey-stafford** [comment]
Note that the "Internet-required data/Satellite orthophoto mosaic (10-0.2m)" layer includes source data from Sentinel 2. See

**Comment by twilamoon-science** [comment]
I think that with the new orthophoto mosaic and the other imagery we have with v3alpha, we are good to go. I'm going to close this ticket.
