### ISSUE TITLE
GEUS Mineral Occurrence

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#624]
Migrated from [Jira](https://nsidc.org/jira/browse/QGR-27): 

[GetCapabilities](http://maps.greenmin.gl/geusmap/ows/32624.jsp?nocache=nocache&whoami=8.44.147.13&typename=mineral_occurrences_v3_external&service=WFS&version=1.0.0&mapname=greenland_portal&request=GetCapabilities&maxfeatures=1)

https://data.geus.dk/greenlanddb/webresources/dodex-report-file/released-report/28819. GEUS requests that users of their services provide a 'whoami' parameter so that they an provide feedback if necessary. Requests omitting this param may be refused or rate-limited (see http://maps.greenmin.gl/geusmap/ows/help/?mapname=greenland_portal&epsg=32624). I suppose we could probably just use our qgreenland email for this, but it might be worth reaching out to them so that they know who we are and why we're frequently fetching their data.

Comment:
> The branch that was started for this work ended up getting deleted, but at this point it would be w/ the outdated config, so best to start from scratch on this one if we decide to add it.

We documented online resourced provided by GEUS as part of this Jira ticket: https://nsidc.org/jira/browse/QGR-47

**Comment by trey-stafford** [comment]
GEUS entry on mineral occurrence data (WFS): https://data.geus.dk/geonetwork/srv/eng/catalog.search#/metadata/8884ead8-45fc-4d1a-ae67-325182cde646

**Comment by trey-stafford** [comment]
Originally the title of this issue indicated adding this as an online layer, but that's not really necessary. The data are only 1.3M in size, uncompressed. With the addition of this layer, our QGreenland core package size is still just under 3GB (just under the size of v2.0.0).

We could tweak the config to add this as an online-only (WFS) layer if we want to though.

**Comment by twilamoon-science** [comment]
Let's add it as a download layer since that sounds easy to do and size-appropriate. The internet-only group should really be reserved for data files too large to include (or other specific internet-access reason).

**Comment by MattF-NSIDC** [comment]
>The internet-only group should really be reserved for data files too large to include (or other specific internet-access reason).

:100:
