### ISSUE TITLE
Keep version number in documentation citation up-to-date with bumpversion

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#634]
This PR removed the version from the citation, but we should add it back and auto-update it:

https://github.com/nsidc/qgreenland/pull/445/files

... Maybe we don't need to do this? Should our citation be generic and version-less? What if a user used the plugin to get some QGreenland layers? I think just citing "QGreenland" without worrying about whether Core or Custom was used is best.

**Comment by twilamoon-science** [comment]
It is valuable to be able to cite with DOI different versions of QGreenland Core, but just for the primary LTR versions. Not sure what that means about citing various versions along the way...

**Comment by MattF-NSIDC** [comment]
@twilamoon-science what do you think about where we landed? We have a citation for the latest version, then all the LTR versions in descending order.

https://qgreenland.readthedocs.io/en/latest/citing.html

**Comment by MattF-NSIDC** [comment]
In case you find stuff you want to continue to tweak, here's the source file! https://github.com/nsidc/qgreenland/blob/main/doc/citing.md

**Comment by twilamoon-science** [comment]
This looks great. Thanks!
Is there a way we might add a link to the part about the "Interacting with Geospatial Data tutorial"? I'm assuming yes, but haven't looked up how to add that to the code yet.
