### ISSUE TITLE
Glacier equilibrium line altitude

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#640]
Migrated from [Jira](https://nsidc.org/jira/browse/QGR-38):

Is this possible or reasonable? Not even sure what this is. Need to do some research!

**Comment by twilamoon-science** [comment]
I don't know of and couldn't find a reasonable data source for this. Honestly, it's pretty difficult metric to produce for Greenland. So we can ignore this for now.

**Comment by MattF-NSIDC** [comment]
@trey-stafford I think we should close the issue (not delete it, of course), and re-open if the situation changes. What do you think?

Closing with this comment, please re-open if you disagree :)
