### ISSUE TITLE
Address feedback for QGreenland v3 alpha(s)

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#674]
Consider last week of July-ish for soliciting feedback. Solicit on QGreenland newsletter + CryoCloud. 

Ensure we solicit feedback early enough that we have time to address it! We plan to release v3 in August.

Consider setting up a Discussion or GH Issue workflow for gathering feedback.

**Comment by trey-stafford** [comment]
We solicited feedback on v3 alpha4 and indicated a deadline of Aug. 6. We received two responses, both of which only addressed  the "What other comments or suggestions do you have for the QGreenland team?"

One response noted that the package worked well with QGIS 3:32.1.

The other response indicated that QGreenland has been useful for field and educational purposes. The reviewer noted that the following could be useful layers:

* 200 m IBCAO bathymetry
* Marine (and lacustrine?) sediment core metadata database
* Greenland margin CTD casts
* Geophysical chirp/seismic lines and metadata w/ links to data

**Comment by MattF-NSIDC** [comment]
Good feedback! Two responses is better than no responses :)

* 200m IBCAO: IIRC in v2 this was clipped to QGreenland boundary. If we were to choose between 200m clipped to QGreenland and 400m clipped to background, which would provide better cost:benefit?
* I had to look up "lacustrine", what a great word. This sounds like a super cheap layer to add, assuming the data is FAIR.
* Same as the previous bullet? Sounds like sparse point data?
* "Links to data" i.e. we have vector elements (lines) with attributes including links to echogram (non-geolocated?) raster data cross-sectioning along the vector element?

**Comment by trey-stafford** [comment]
> * 200m IBCAO: IIRC in v2 this was clipped to QGreenland boundary. If we were to choose between 200m clipped to QGreenland and 400m clipped to background, which would provide better cost:benefit?

In QGreenland v2 we had the full 400m IBCAO grid. This wasn't clipped at all. It doesn't completely cover either of our boundaries (data or background).

That said, there is a 200m IBCAO dataset [here](https://www.gebco.net/data_and_products/gridded_bathymetry_data/arctic_ocean/). The GEBCO grid (from which IBCAO is based), is available at a resolution of 0.004166666666667 degrees lat/lon. Our `gdalwarp` step sets the resolution of our reprojection of this dataset to 400x400 meters, to be consistent with the original 400m IBCAO grid we included in v2. We could change this.

**Comment by MattF-NSIDC** [comment]
Ah, forgot about #584

**Comment by twilamoon-science** [comment]
Re: these feedback items:
- Marine (and lacustrine?) sediment core metadata database
- Greenland margin CTD casts

I don't think that synthesis databased exist for either of these data types. The NASA Oceans Melting Greenland (OMG) mission did do quite a few CTD casts (https://omg.jpl.nasa.gov/data/) but that is just one source. I do know folks are thinking (perhaps even working) about gathering these data together, but I don't think anything has been produced yet. I think these requests fall into the category of things people wish QGreenland did (create new synthesized databases) but are not actually activities that we do.

**Comment by MattF-NSIDC** [comment]
>NASA Oceans Melting Greenland (OMG) 

This acronym is so lovable! This person should be in charge of all of NASA's acronyms from now on.

**Comment by twilamoon-science** [comment]
You may not be surprised that the lead PI on the NASA OMG mission also has an alter ego as Climate Elvis (https://www.youtube.com/watch?v=WGfKRfyhvd0). I think it will be heard to beat this acronym for all future missions.

**Comment by trey-stafford** [comment]
Created new issues to address each of these (currently in "No Status"):

* https://github.com/nsidc/qgreenland/issues/734
* https://github.com/nsidc/qgreenland/issues/735
* https://github.com/nsidc/qgreenland/issues/736
* https://github.com/nsidc/qgreenland/issues/737

Closing this issue in favor of addressing each component of this feedback via the issues above!
