### ISSUE TITLE
Distinguish code/software and data citations and update authorship

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#702]
Follow-up on conversation here: https://github.com/nsidc/qgreenland/pull/701#discussion_r1279993889

How should we cite our work products under this grant?

Twila is the PI and long-term responsible party for the work under this grant and cited as the first author of QGreenland on our doc's citation page. How should we communicate the authorship of the code? Should we do that in the DOI entry (`CITATION.cff`)?

Or should we treat QGreenland the _package_ as "data", citing Twila as first author, and the _source code_ (this repo) as "software", citing Trey and myself as co-equal first authors? This seems fairly in line with other projects I've worked on.

@twilamoon-science @trey-stafford

**Comment by MattF-NSIDC** [comment]
We can create a Zenodo DOI for the package separately from the software, too. The upload limit is 50GB.

**Comment by twilamoon-science** [comment]
This item has been on my mind. What steps have you already taken to finalize this? In particular, I think that the software citation really should have @MattF-NSIDC and @trey-stafford as first authors (we can add an asterisk so that it is a shared first authorship). I'm not sure that we functionally have more than 1 think to cite with v3, so this would be the v3 citation. When we someday write a description paper for QGreenland, I can lead author that.

**Comment by MattF-NSIDC** [comment]
@twilamoon-science thanks for sharing your thoughts! We've not taken any concrete steps, have just been chatting so far. Here are my thoughts coming out of those chats:

I think our situation is not identical, but is analogous to a project which produces software that produces a dataset: _QGreenland_ software produces the _QGreeenland Core_ dataset (and eventually, others). Often the dataset citation for those other projects will have PI as first author, and the software citation will be the relevant developers.

_QGreenland Core_ is like our dataset, so I think you should be lead author on that. And I think it makes sense for the dataset citation to be the primary citation we display on ReadTheDocs, which is primarily aimed at users. The real final product of this work (so far) has been the dataset, and the software is a means to get there.

The software citation I feel can/should live only on GitHub/Zenodo. Or we could display a citation for QGreenland Core and QGreenland software both together on ReadTheDocs.

**Comment by MattF-NSIDC** [comment]
Notes from meeting:

* Software/data separate citations sound good
* Citation on website and on docs that match
* Both software and data citation in both place
* A short description of the difference between the two.
* Ensure there's a note about citing source data

**Comment by MattF-NSIDC** [comment]
Shouldn't close this until QGreenland the dataset has a DOI. WIP.

**Comment by MattF-NSIDC** [comment]
https://zenodo.org/record/8247896
