### ISSUE TITLE
Ensure all "palletted/unique values" colormaps have descriptive labels

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#710]
E.g. some pallettes have labels like `1`, `2`, `3`, when they should be `land`, `lake`, and `ocean`.

Ex:

* PROMICE mask (1km)
* Grounded ice mask (1km)

**Comment by trey-stafford** [comment]
Examples include the "PROMICE mask (1km)" and "Grounded ice mask (1km)" layers. The layer descriptions include mappings between values and meanings but the legend should show this too.

For an example of a classification map that includes labels, see the "Vegetation classification map (1km)" layer.

**Comment by MattF-NSIDC** [comment]
Thanks! I just couldn't recall what we were looking at on Zoom and wanted to get the general idea written down anyway :) Updating description...
