### ISSUE TITLE
Review all documentation for v3 accuracy

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#719]
Only focusing on user docs.

- [x] Reference
- [x] Tutorial
- [x] How to
- [ ] Discussion

**Comment by trey-stafford** [comment]
Also review QuickStartGuide.pdf in package. Needs updating.

**Comment by twilamoon-science** [comment]
@alysethurber is working on related language for the website update and we can probably produce this 1-pager from that work.
