### ISSUE TITLE
Re-organize "Internet required" layers

### ISSUE THREAD

**Issue by trey-stafford** [nsidc/qgreenland#727]
Consider subgroups or some other way to indicate internet-required layers in the layers panel.

Some (e.g., the [geological map from geus](https://github.com/nsidc/qgreenland/pull/725)) might be best placed alongside layers that are in the "Geology" group. Maybe we could have "Internet-required" subgroups under appropriate discipline-specific groups? E.g.,

* "Geology/Internet-required/..."
* "Basemaps/Internet-required/..."

**Comment by MattF-NSIDC** [comment]
I think I like internet-required layers being a top-level group, but I don't have reasoning to support it :P

**Comment by twilamoon-science** [comment]
I like the idea of distributing to appropriate groups, but with a subgroup still called internet-required data. My reasoning... It would be nice for folks to find the geologic maps next to each other within that group. Then most others fits with basemaps, and those are already grouped right next to the internet-only layers.

**Comment by MattF-NSIDC** [comment]
I think you changed my mind :P

**Comment by trey-stafford** [comment]
Rename "Internet-required data" to "Internet required" (drop "data"). We plan to move these into appropriate subgroups as described above!

**Comment by trey-stafford** [comment]
Thoughts on re-organizations:

The image mosaics & the satellite orthophoto could either go into `Basemaps` or maybe in a new `Satellite imagery` group just above it? In that case we could indicate that it's internet required at the root (e.g., `Satellite imagery (internet required)`).

The new topographic map of Greenland could be considered a basemap. My initial thought was to put it with Bedmachine , because it provides topographic information. That would put it in "Terrain models". I'm not sure this topo map is really considered a terrain model though. It shows terrain & other reference information. I lean toward the first option (basemap). 

The geological map would end up in the "Geology" subgroup.

The blue marble shaded relief and bathymetry layer could go into the above mentioned `Satellite imagery (internet required)`, `Oceanography`, or (I think most fittingly) in Basemaps.

In the simplest scheme, everything except the geological map would end up under  "Basemaps":

* "Basemaps/Internet required"
   * "Greenland image mosaic 2019 (10m)"
   * "Greenland image mosaic 2015 (15m"
   * "Satellite orthophoto mosaic (10-0.2m)"
   * "Topographic map of Greenland"
   * "Blue Marble shaded relief and Bathymetry (500m)"
* "Geology/Internet required"
   * "Geological Map (1:500 000)"

**Comment by MattF-NSIDC** [comment]
> The image mosaics & the satellite orthophoto could either go into Basemaps or maybe in a new Satellite imagery group just above it? In that case we could indicate that it's internet required at the root (e.g., Satellite imagery (internet required)).

I think I prefer the latter!

>The new topographic map of Greenland could be considered a basemap. My initial thought was to put it with Bedmachine , because it provides topographic information. That would put it in "Terrain models". I'm not sure this topo map is really considered a terrain model though. It shows terrain & other reference information. I lean toward the first option (basemap).

I agree with basemap > terrain model here; but maybe this warrants another category, e.g. "Curated maps"? The topomap is definitely in a different category than the natural earth basemaps. :shrug: 

>The blue marble shaded relief and bathymetry layer could go into the above mentioned Satellite imagery (internet required), Oceanography, or (I think most fittingly) in Basemaps.

I think basemaps is also most fitting here.

What about this?:

* `Geology / Internet required` (or `Curated maps / Internet required`?)
    * Geological map
* `Satellite imagery (internet required)`
    * image mosaics, orthophoto
* `Basemaps / Internet required`
    * Blue marble

Or (I like this less):

* `Geology / Internet required` (or `Curated maps / Internet required`?)
    * Geological map
* `Basemaps`
    * `Internet required`
        * Blue marble
        * `Satellite imagery`
            * image mosaics
            * orthophoto

**Comment by trey-stafford** [comment]
> What about this?:
> 
>     * `Geology / Internet required` (or `Curated maps / Internet required`?)
>       
>       * Geological map
> 
>     * `Satellite imagery (internet required)`
>       
>       * image mosaics, orthophoto
> 
>     * `Basemaps / Internet required`
>       
>       * Blue marble

I like this too!

**Comment by MattF-NSIDC** [comment]
@trey-stafford I left out the SDFI topo map. Where do you think that should go?

**Comment by twilamoon-science** [comment]
What do both of you think about putting SDFI topo map at top of basemaps group? I think it will be a layer used a lot and I'm trying to think of a high-viz location for it.

**Comment by MattF-NSIDC** [comment]
Just to be 100% clear, you mean in `Basemaps / Internet required` above the blue marble layer? I'm good with that.

**Comment by twilamoon-science** [comment]
Yes, that's what I was thinking. And that the Internet required subgroup goes above the other layers. ?

**Comment by MattF-NSIDC** [comment]
Got it, working on implementation now! 

>Internet required subgroup goes above the other layers.

That's how I've got it :)
