### ISSUE TITLE
Apply v3 feedback from Twila

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#738]
https://nsidc.slack.com/archives/CRB96FG68/p1689705184038139

* Opening up the file in QGIS 3.32 was smooth as butter. :butter:

- [x] The bottom 3 layers in the "internet-required data" group have dropdown arrows on the left, but nothing that appears when you click it.

    ![image](https://github.com/nsidc/qgreenland/assets/18539827/15d449bd-f8bf-4749-aece-3cf12f4a120e)

- [ ] I don't see any apparent date information for the 'global administrative divisions' layer. Browsing around the citation URL also didn't provide leads. Is it easy for us to know the date of this data version and add to metadata?

- [x] Love the new buildings and roads layers! (Also, the full reference section looks great). With our new internet-required data layers, these all create amazing local detail. :heart: 

- [ ] Under Geophysics > Heat flux we have 2 different titles that acknowledge data authors. We don't do this for other layers. Consider removing that from title and simply ensuring full metadata information. Could consider replacing with a date/date range re: measurements instead.  >> follow up: looks like data compilation, so just title without date(s) looks like best option (edited) 

- [x] I think it would be a good idea to update BedMachine title to "BedMachine v5"

**Comment by MattF-NSIDC** [comment]
>The bottom 3 layers in the "internet-required data" group have dropdown arrows on the left, but nothing that appears when you click it.

This is an artifact of the different ways the data is exposed over the internet by the data providers. The image mosaics are displayed as "multiband color" because they're based on an online VRT file that defines multiple bands. The orthophotos, topomap, and bathymetry layers are all WMS layers understood as "singleband color data" by QGIS.

**Comment by MattF-NSIDC** [comment]
> I don't see any apparent date information for the 'global administrative divisions' layer. Browsing around the citation URL also didn't provide leads. Is it easy for us to know the date of this data version and add to metadata?


Looks like the most recent version 5.1.0 was released on 2022-05-13. I don't think that necessarily means that all boundaries are correct and valid as of that date. We should probably clear this dataset `ne_states_provinces` from our cache to ensure the latest version is grabbed on our next compilation.

**Comment by MattF-NSIDC** [comment]
>Under Geophysics > Heat flux we have 2 different titles that acknowledge data authors. We don't do this for other layers. Consider removing that from title and simply ensuring full metadata information. Could consider replacing with a date/date range re: measurements instead. >> follow up: looks like data compilation, so just title without date(s) looks like best option (edited)

This was a point of discussion when we first added the two layers. One author refers to flux, the other to flow (same units, I think they're the same thing). Without adding the authors, distinguishing between them was difficult.

>just title without date(s) looks like best option

This would give us:

* `Heat Flux/Heat flow/Flow measurement locations`
* `Heat Flux/Heat flow/Flow from multiple observations`
* `Heat Flux/Flux from ice cores`

Maybe we should rename `Heat flow` to `Heat flow from machine learning`?

**Comment by MattF-NSIDC** [comment]
>I think it would be a good idea to update BedMachine title to "BedMachine v5"


https://github.com/nsidc/qgreenland/pull/741

**Comment by MattF-NSIDC** [comment]
@trey-stafford could use input on:

https://github.com/nsidc/qgreenland/issues/738#issuecomment-1683033665
https://github.com/nsidc/qgreenland/issues/738#issuecomment-1683038934

**Comment by trey-stafford** [comment]
> We should probably clear this dataset `ne_states_provinces` from our cache to ensure the latest version is grabbed on our next compilation.

Sounds like a good idea to me!

**Comment by twilamoon-science** [comment]
Re: 'global administrative divisions' layer... We aren't in the business of saying if the data are correct, but I do think we should record something about when a dataset is published and/or when we access it. That was my thought re: the metadata, rather than being able to say something about the boundary accuracy for a specific date. Does that make sense for implementation?

**Comment by trey-stafford** [comment]
> > Under Geophysics > Heat flux we have 2 different titles that acknowledge data authors. We don't do this for other layers. Consider removing that from title and simply ensuring full metadata information. Could consider replacing with a date/date range re: measurements instead. >> follow up: looks like data compilation, so just title without date(s) looks like best option (edited)
> 
> This was a point of discussion when we first added the two layers. One author refers to flux, the other to flow (same units, I think they're the same thing). Without adding the authors, distinguishing between them was difficult.
> 
> > just title without date(s) looks like best option
> 
> This would give us:
> 
>     * `Heat Flux/Heat flow/Flow measurement locations`
> 
>     * `Heat Flux/Heat flow/Flow from multiple observations`
> 
>     * `Heat Flux/Flux from ice cores`
> 
> 
> Maybe we should rename `Heat flow` to `Heat flow from machine learning`?

I think you're right about flux and flow referring to the same phenomena. Part of the reason we stuck with those terms for those layers is because the dataset title:

* Greenland Geothermal Heat Flow Database and Map
* Geothermal heat flux distribution for the Greenland ice sheet, derived by combining a global representation and information from deep ice cores

I think the idea of renaming the "Heat flow" subgroup to "Heat flow from machine-learning" seems reasonable.

**Comment by trey-stafford** [comment]
> I do think we should record something about when a dataset is published and/or when we access it.

Agreed. We should update the citation to indicate the version of the data. We can also add the date accessed.

Note that we do have a mechanism for injecting the access date into the citation, but it is done on a case-by-case basis (not all dataset citations have this)

**Comment by twilamoon-science** [comment]
Re: Heat Flux

1) Agree it's no problem to keep "heat flux" and "heat flow", reflecting the dataset names
2) What about keeping "heat flow", but changing "flow from multiple observations" to "gridded heat flow". Then we could copy/paste the related publication abstract into the metadata (we do this for some other layers). That abstract explains the method.

**Comment by MattF-NSIDC** [comment]
https://github.com/nsidc/qgreenland/issues/742

**Comment by MattF-NSIDC** [comment]
>Agreed. We should update the citation to indicate the version of the data. We can also add the date accessed.

>Note that we do have a mechanism for injecting the access date into the citation, but it is done on a case-by-case basis (not all dataset citations have this)

I think we need to use this for the natural earth layer. The version number is not encoded in the URL, they seem to silently replace the file with the new one every time.

**Comment by MattF-NSIDC** [comment]
#743

**Comment by MattF-NSIDC** [comment]
#744

**Comment by MattF-NSIDC** [comment]
@twilamoon-science @trey-stafford are you OK with this issue being closed, and rolling forward with the issues I created above? If not, please re-open and we can continue discussion :)
