### ISSUE TITLE
Write project as `.qgz`

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#777]
We currently get an extra `qgreenland_attachments.zip` file because we write to `.qgs`

https://gis.stackexchange.com/questions/441331/qgis-creating-attachments-zip-files-in-project-directory

We hadn't noticed it until today, nice :eyes: @twilamoon-science

**Comment by trey-stafford** [comment]
This change needs to be accompanied by updates to documentation.
