### ISSUE TITLE
Post v3 release announcement in GH Discussions (workshops + main repo)

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/qgreenland#789]

**Comment by MattF-NSIDC** [comment]
https://github.com/orgs/qgreenland-workshop-2023-researcher/discussions/173

**Comment by trey-stafford** [comment]
I updated the links in the above mentioned posts to link to the package proxied through nsidc.org: https://nsidc.org/qgreenland/packages/v3.0.0/QGreenland_v3.0.0.zip

This allows us to inherit the nsidc.org SSL cert and avoid warnings to users about the connection being insecure.

**Comment by MattF-NSIDC** [comment]
Thank you, I totally forgot about that.
